---
apiVersion: v1
kind: ConfigMap
metadata:
  name: CommonConfigMap
  namespace: default
  labels:
    managed-by: flux
    auto-created: "true"
data:
  environment: "shared"
  cluster: "my-cluster"
  managed-by: "flux-config-connector"
  created-at: "2025-01-09"
  description: "Common configuration shared across all namespaces"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: CommonConfigMap
  namespace: flux-system
  labels:
    managed-by: flux
    auto-created: "true"
data:
  environment: "shared"
  cluster: "my-cluster"
  managed-by: "flux-config-connector"
  created-at: "2025-01-09"
  description: "Common configuration shared across all namespaces"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: CommonConfigMap
  namespace: kube-system
  labels:
    managed-by: flux
    auto-created: "true"
data:
  environment: "shared"
  cluster: "my-cluster"
  managed-by: "flux-config-connector"
  created-at: "2025-01-09"
  description: "Common configuration shared across all namespaces"
