---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config-template
  namespace: config-connector-system
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kustomize-functions/create-setters:v0.1.0
data:
  template.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: CommonConfigMap
      namespace: TARGET_NAMESPACE
    data:
      environment: "shared"
      cluster: "my-cluster"
      managed-by: "flux-config-connector"
      created-at: "2025-01-09"
---
apiVersion: v1
kind: Secret
metadata:
  name: common-secret-template
  namespace: config-connector-system
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kustomize-functions/create-setters:v0.1.0
type: Opaque
data:
  # Base64 encoded values
  shared-key: c2hhcmVkLXNlY3JldC1rZXk=  # "shared-secret-key"
  cluster-id: bXktY2x1c3Rlcg==  # "my-cluster"
stringData:
  template.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: CommonSecret
      namespace: TARGET_NAMESPACE
    type: Opaque
    data:
      shared-key: c2hhcmVkLXNlY3JldC1rZXk=
      cluster-id: bXktY2x1c3Rlcg==
      environment: c2hhcmVk  # "shared"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-config-connector
  namespace: config-connector-system
data:
  kustomization.yaml: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    
    resources:
    - common-configmap.yaml
    - common-secret.yaml
    
    transformers:
    - namespace-transformer.yaml
    
    generators:
    - namespace-generator.yaml
  
  namespace-transformer.yaml: |
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: namespace-transformer
    namespace: TARGET_NAMESPACE
    setRoleBindingSubjects: none
    unsetOnly: false
    fieldSpecs:
    - path: metadata/namespace
      create: true
  
  namespace-generator.yaml: |
    apiVersion: builtin
    kind: ConfigMapGenerator
    metadata:
      name: namespace-list
    literals:
    - namespaces=default,kube-system,flux-system,config-connector-system
  
  common-configmap.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: CommonConfigMap
    data:
      environment: "shared"
      cluster: "my-cluster"
      managed-by: "flux-config-connector"
      created-at: "2025-01-09"
  
  common-secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: CommonSecret
    type: Opaque
    data:
      shared-key: c2hhcmVkLXNlY3JldC1rZXk=
      cluster-id: bXktY2x1c3Rlcg==
      environment: c2hhcmVk
